service: compare-plate-apis
runtime: custom
env: flex
entrypoint: waitress-serve --host=0.0.0.0 --port=8080 main:main_app
instance_class: F1

automatic_scaling:
  min_num_instances: 1
  max_num_instances: 5
  cpu_utilization:
    target_utilization: 0.65

handlers:
  - url: /.*
    script: auto